name: Build Image

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master
    paths-ignore :
      - '.github/**'
  pull_request:
    branches:
      - master
    paths-ignore:
      - '.github/**'

jobs:
  bake:
    strategy :
      fail-fast: false
      matrix :
        dfiles : [ ./docker/docker-py3-kms/Dockerfile, ./docker/docker-py3-kms-minimal/Dockerfile ]
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: set publish to true
        run:  echo "PUBLISH=false" >> $GITHUB_ENV
      - name: set publish to false is from pull request
        if: github.event_name == 'pull_request'
        run: echo "PUBLISH=false" >> $GITHUB_ENV
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: all
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        continue-on-error : true
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Login to GitHub Container Registry
        continue-on-error : true
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ${{ matrix.dfiles }}
          platforms: linux/amd64,linux/386,linux/arm64/v8,linux/arm/v7,linux/arm/v6
          push: ${{ env.PUBLISH }}
          tags: pykmsorg/py-kms:python3,ghcr.io/py-kms-organization/py-kms:python3
