name : linting both dockerfile

on: [push, pull_request]

jobs :
  lint :

    runs-on : ubuntu-latest

    steps :
      - uses : actions/checkout@v2
      - name : Set up Python 3.
        uses : actions/setup-python@v1
        with :
          python-version : 3
      - uses : actions/checkout@v2
      - name : flake8 Lint
        uses : py-actions/flake8@v1
        with :
          path : "py-kms"
      - name : Install dependencies
        run : |
          python -m pip install --upgrade pip
          pip install pylint
      - name : Analysing the code with pylint
        run : |
          pylint `ls -R|grep .py$|xargs`
